spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: google
        uri: https://www.google.com
        predicates:
        - Path=/google5
        filters:
        - RewritePath=/google5(?<segment>/?.*), /${segment}

server:
  port: 9090

logging:
  level:
    com.ub: debug
    org.springframework.cloud.gateway: debug